FROM node:24-bookworm

WORKDIR /app

EXPOSE 4200

CMD ["sh", "-c", "npm install && npm start"]



# FROM node:24-bookworm

# WORKDIR /app

# COPY package*.json ./

# RUN npm install

# COPY . .

# EXPOSE 4200

# CMD ["npm", "start"]